#!/bin/sh
# Test ignoring case

. "${srcdir=.}/init.sh"; path_prepend_ ../src

fail=0

printf 'Funky Stuff\n' >a
printf 'fUNKy stuFf\n' >b

diff -i a b >out || fail=1
compare /dev/null out || fail=1

require_utf8_locale_

echo 'AĀȀΆΑАӐḀἈⒶꞺＡ𐐀-Δ' >a
echo 'aāȁάαаӑḁἀⓐꞻａ𐐨-δ' >b

diff -i a b >out || fail=1
compare /dev/null out || fail=1

Exit $fail
